from ROOT import gStyle
print 'Using rootlogon.py'
gStyle.SetStatColor(0)
gStyle.SetCanvasColor(0)
gStyle.SetFrameFillColor(0)
gStyle.SetPadColor(0)
gStyle.SetPadBorderMode(0)
gStyle.SetCanvasBorderMode(0)
gStyle.SetFrameBorderMode(0)
gStyle.SetOptStat(1110)
gStyle.SetStatH(0.2)
gStyle.SetStatW(0.2)
gStyle.SetStatX(0.99)
gStyle.SetTitleColor(1)
gStyle.SetTitleFillColor(0)
gStyle.SetTitleStyle(0)
gStyle.SetTitleBorderSize(0)
gStyle.SetTitleFontSize(0.04)
gStyle.SetTitleY(1.)
gStyle.SetTitleX(.1)
